In [1]:
#Import Libraries
import numpy as np
import matplotlib.pyplot as mp
import pandas as pd

In [2]:
#Import Dataset
dataset=pd.read_csv("creditcard.csv")
dataset=dataset.sample(frac=0.1,random_state=1)
print(dataset.shape)
x=dataset.iloc[:,1:30].values
y=dataset.iloc[:,30].values

(28481, 31)


In [3]:
print(x.shape)

(28481, 29)


In [4]:
print(y.shape)

(28481,)


In [5]:
#Missing values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:30])
x[:,1:30]=imputer.transform(x[:,1:30])

In [6]:
print(x.shape)

(28481, 29)


In [7]:
#Splitting dataset into tranning and test set
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state = 0)

In [8]:
print("xtrain.shape : ", xtrain.shape)
print("xtest.shape  : ", xtest.shape)
print("ytrain.shape : ", ytrain.shape)
print("xtest.shape  : ", xtest.shape)

xtrain.shape :  (21360, 29)
xtest.shape  :  (7121, 29)
ytrain.shape :  (21360,)
xtest.shape  :  (7121, 29)


In [9]:
#Fatures Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [10]:
print("Standardised Training Set : \n", xtrain[0])

Standardised Training Set : 
 [ 0.74984069 -0.55707311 -0.01889536 -1.24005593 -0.44355532  0.33702988
 -0.81565277  0.04258148 -2.01479241  1.41516826  0.58482045  0.10822904
  1.71393924 -0.38952174  0.08658512 -0.23243629  0.05886731  0.29503432
  0.14072466 -0.28589618 -0.26309703 -0.16827534 -0.15782053 -1.88604126
  0.91947294 -0.26649721  0.11802904  0.00259242 -0.26449705]


In [11]:
# KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(xtrain, ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(xtest)
cm = confusion_matrix(ytest, y_pred)
print(cm)
accuracy_score(ytest, y_pred)
Accuracy_Decison = ((cm[0][0] + cm[1][1]) / cm.sum()) *100
print("Accuracy_Decison    : ", Accuracy_Decison)
Error_rate = ((cm[0][1] + cm[1][0]) / cm.sum()) *100
print("Error_rate  : ", Error_rate)


[[7111    1]
 [   2    7]]
Accuracy_Decison    :  99.9578710855217
Error_rate  :  0.04212891447830361


In [13]:
#Decision Tree Classification
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(xtrain, ytrain)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred=classifier.predict(xtest)
cm = confusion_matrix(ytest, y_pred)
print(cm)
accuracy_score(ytest, y_pred)
Accuracy_Decison = ((cm[0][0] + cm[1][1]) / cm.sum()) *100
print("Accuracy_Decison    : ", Accuracy_Decison)
Error_rate = ((cm[0][1] + cm[1][0]) / cm.sum()) *100
print("Error_rate  : ", Error_rate)

[[7106    6]
 [   3    6]]
Accuracy_Decison    :  99.87361325656508
Error_rate  :  0.12638674343491083


In [15]:
#Random Tree Classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(xtrain, ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [16]:
y_pred=classifier.predict(xtest)

In [17]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(ytest, y_pred)
print(cm)
accuracy_score(ytest, y_pred)
Accuracy_Decison = ((cm[0][0] + cm[1][1]) / cm.sum()) *100
print("Accuracy_Decison    : ", Accuracy_Decison)
Error_rate = ((cm[0][1] + cm[1][0]) / cm.sum()) *100
print("Error_rate  : ", Error_rate)

[[7112    0]
 [   5    4]]
Accuracy_Decison    :  99.92978514253616
Error_rate  :  0.07021485746383935
